GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Blog title",
    "author": "Blog author",
    "url": "myblog.url",
    "likes": 1
}

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Blog title",
    "author": "Blog author",
    "url": "myblog.url"
}

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "author": "Blog author",
    "likes": 1
}