GET https://polar-citadel-35304.herokuapp.com/api/persons

###

POST https://polar-citadel-35304.herokuapp.com/api/persons

###

POST https://polar-citadel-35304.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Louise Leblanc",
  "number": "1-123-9876"
}

###

POST https://polar-citadel-35304.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Louise Leblanc"
}

###

POST https://polar-citadel-35304.herokuapp.com/api/persons
Content-Type: application/json

{
  "number": "0-000-0000"
}

###