GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Louise Leblanc",
  "number": "1-123-9876"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Louise Leblanc"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "0-000-0000"
}

###